Домашнє завдання №1

23 варіант

In [1]:
import numpy as np

1. Створіть одновимірний масив (вектор) зі зростаючою геометричною послідовністю, де кожне наступне число більше попереднього в 2 рази, починаючи з 2, та виведіть його значення. 

In [2]:
value = 2
num_elements = 10
result = np.geomspace(value, value * (2 ** (num_elements - 1))num_elements)
print(result)

SyntaxError: invalid syntax. Perhaps you forgot a comma? (4191595280.py, line 3)

2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його оберненими значеннями натуральних чисел, починаючи з 1, та виведіть його значення. 

In [ ]:
a = 1 / np.arange(1, 3 * 3 + 1).reshape(3, 3)
print(a)

[[1 2 0]
 [1 2 0]
 [1 2 0]]


3. Створіть масив розміром 10x10, заповніть його випадковими дійсними числами в діапазоні від -10 до 10 та знайдіть максимальний елемент. 

In [ ]:
a = np.random.randint(-11, 11, (10,10))
print(a)

[[36 31 36 37 46 26 48 37 34]
 [15  8  3 39 25  3  3  4  5]
 [10 13 10 45 31 42 23 43 39]
 [ 2 12 12  5 15 31 46 34  3]
 [50  4 39 26  4 50 42 10  4]
 [10 45 17 30 49 46 25 40 26]
 [42 36 50 47 40 13  9 43 36]
 [31 31 18 27 28 40  7 43 49]
 [17  1  8 25  5 21 16 15 41]]
Відсоток чисел, які діляться на 3 без остачі:
33.33333333333333


4. Створіть масив розміром 3x3, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного стовпця, менших за 0.5. 

In [ ]:
a = np.random.rand(3, 3)
print(a)

[[-0.42794571  0.81661076  0.38225535  0.44582265]
 [-0.16787406 -0.06212908  0.0096856  -0.03251983]
 [-0.42103143 -0.15178659  0.77724594  0.81732274]
 [-0.78623616 -0.08596231 -0.31481615  0.78652367]]


5. Створіть два одновимірних масиви розміром 6, заповніть їх випадковими дійсними числами від -2 до 2 та виконайте на них поелементні операції додавання, віднімання та множення.

In [ ]:
a = np.random.randint(1, 11, size=6)
b = np.random.randint(1, 11, size=6)

print("a = ", a)
print("b = ", b)

print("a + b = ", a + b)
print("a - b = ", a - b)
print("a * b = ", a * b)

a =  [4 4 4 5 5 4 1]
b =  [1 5 1 2 4 3 1]
a + b =  [5 9 5 7 9 7 2]
a - b =  [ 3 -1  3  3  1  1  0]
a * b =  [ 4 20  4 10 20 12  1]


6. Створіть два вектори розміром 8, заповніть їх довільними цілими числами та знайдіть їх скалярний добуток.

In [ ]:
a = np.random.randint(1, 11, size=4)
b = np.random.randint(1, 11, size=4)

dot_a_b = np.dot(a, b)

print("a = ", a)
print("b = ", b)
print("Скалярний добуток векторів дорівнює:", dot_a_b)

a =  [ 1 10  2  2]
b =  [ 5  7 10  5]
Скалярний добуток векторів дорівнює: 105


7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 8 та перемножте їх між собою.

In [ ]:
a = np.random.randint(1, 8, size=(2, 2))
b = np.random.randint(1, 8, size=(2, 3))

dot_a_b = np.dot(a, b)

print("a = ", a)
print("b = ", b)
print("Результат множення матриць:")
print(dot_a_b)

a =  [[10 11 15]
 [12 10  3]]
b =  [[15 12  4  4]
 [ 9 13  2  6]
 [14 11 12 15]]
Результат множення матриць:
[[459 428 242 331]
 [312 307 104 153]]


8. Створіть матрицю розміром 2x2, заповніть її випадковими цілими числами в діапазоні від 1 до 15 та знайдіть її обернену матрицю.

In [ ]:
a = np.random.randint(1, 15, size=(2, 2))
print("Вихідна матриця:")
print(a)

# перевірка, чи можна знайти обернену матрицю
if np.linalg.det(a) == 0:
    print("Матриця не має оберненої матриці.")
else:
    # знаходження оберненої матриці
    inv_a = np.linalg.inv(a)
    print("Обернена матриця:")
    print(inv_a)


Вихідна матриця:
[[ 9  3]
 [ 8 11]]
Обернена матриця:
[[ 0.14666667 -0.04      ]
 [-0.10666667  0.12      ]]


9. Створіть матрицю розміром 7x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [ ]:
a = np.random.rand(7, 3)
print(a)

a_transp = np.transpose(a)
print("Транспонована матриця:")
print(a_transp)

[[ 9  7 14]
 [ 3  3  8]
 [13  6 15]]
Транспонована матриця:
[[ 9  3 13]
 [ 7  3  6]
 [14  8 15]]


10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть матрицю випадковими цілими числами в діапазоні від 1 до 10, а вектор - випадковими дійсними числами від 0 до 1, і знайдіть добуток матриці на вектор.

In [ ]:
matr = np.random.randint(1, 10, size=(3, 4))
vect = np.random.randint(1, 10, size=4)
print("Матриця:")
print(matr)
print("Вектор:")
print(vect)

print("Результат множення матриці на вектор:")
result = np.dot(matr, vect)
print(result)

Матриця:
[[8 7 8 9]
 [8 8 1 6]
 [6 1 4 7]]
Вектор:
[6 7 1 5]
Результат множення матриці на вектор:
[132 112  13 110]


11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими дійсними числами від 0 до 1, і знайдіть суму елементів матриці, які більше за відповідний елемент вектору.

In [ ]:
matr = np.random.rand(2, 3)
vect = np.random.rand(3)
print("Матриця:")
print(matr)
print("Вектор:")
print(vect)

print("Результат множення матриці на вектор:")
result = np.dot(matr, vect)
print(result)

Матриця:
[[0.63729446 0.9940453  0.83693198]
 [0.38383391 0.20073264 0.27151817]]
Вектор:
[0.86303873 0.40412388 0.13380287]
Результат множення матриці на вектор:
[1.06371114 0.4487143 ]


12. Створіть дві матриці розміром 6x6, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть суму елементів першого рядка першої матриці. 

In [ ]:
a = np.random.randint(1, 11, size=(2, 2))
b = np.random.randint(1, 11, size=(2, 2))
print("Перша матриця:")
print(a)
print("Друга матриця:")
print(b)

print("Поелементне множення через multiply:")
result = np.multiply(a, b)
print(result)
print("Поелементне множення через *:")
print(a*b)

Перша матриця:
[[ 3 10  3  1  8  6  9  9]
 [ 6  9  7  3  3  2  6  6]
 [ 8  5 10  3  5  2 10  8]
 [ 9  2  7  4  9  7  5  7]
 [10  5  3  2  7 10 10  1]
 [ 3  4  4  3  4  8  8  4]
 [ 7  4  4  3  6  7  8  9]
 [ 5  3 10  4  3 10  3  5]]
Друга матриця:
[[ 9  8  2  1  6  3  2  4]
 [10  2  3  6  9  2  8  2]
 [ 4  2  7  9 10  6  5  7]
 [10  9  5  5  8  9  1  3]
 [ 7 10  8  4  8  5  5  8]
 [ 3  8  4  6  7  6  1  4]
 [ 4 10  2  6  7  6  7  7]
 [ 8  3 10  3  8  6  7  1]]
Поелементне множення через multiply:
[[  9 100   9   1  64  36  81  81]
 [ 36  81  49   9   9   4  36  36]
 [ 64  25 100   9  25   4 100  64]
 [ 81   4  49  16  81  49  25  49]
 [100  25   9   4  49 100 100   1]
 [  9  16  16   9  16  64  64  16]
 [ 49  16  16   9  36  49  64  81]
 [ 25   9 100  16   9 100   9  25]]
0


13. Створіть дві матриці розміром 5x5, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть добуток їх елементів.

In [ ]:
a = np.random.randint(1, 11, size=(5, 5))
b = np.random.randint(1, 11, size=(5, 5))
print("Перша матриця:")
print(a)
print("Друга матриця:")
print(b)

print("Добуток матриць:")
result = np.dot(a, b)
print(result)

Перша матриця:
[[ 0.08148991 -0.20853894  0.85086458 -0.34644989  0.11926897 -0.49051397
   0.87522234]
 [-0.28719658 -0.69817446  0.55093823  0.05155354  0.57337949 -0.29434478
  -0.48688465]
 [-0.37316636 -0.66628478  0.25488014 -0.13378394  0.36105211 -0.41880197
   0.3809587 ]
 [-0.94264624  0.44613311 -0.2798022  -0.97133143  0.90955284  0.15385205
   0.54812947]
 [-0.21939635 -0.67456088  0.96919209  0.10959683  0.69293078  0.26678481
  -0.26075163]
 [ 0.59842714 -0.54291642  0.26987279  0.57777456  0.69608324 -0.50969722
   0.2358958 ]
 [ 0.80681873 -0.3837212  -0.75091821 -0.80967098  0.26372389 -0.61363412
   0.61732189]]
Друга матриця:
[[-0.83931703 -0.39988376 -0.93176597 -0.03254833  0.0426383  -0.9991055
  -0.515936  ]
 [ 0.9202801   0.10699783 -0.73167154 -0.64756485 -0.19760789 -0.93342324
   0.60715077]
 [-0.77168212  0.90406291 -0.60265544  0.4240593  -0.55090321  0.60950597
   0.05725341]
 [-0.80604879 -0.93244119  0.70800076 -0.33898121  0.85191587 -0.04859868
   0.7

14. Створіть матрицю розміром 11x11, заповніть її випадковими дійсними числами в діапазоні від -10 до 10 та знайдіть суму елементів матриці, які більше за їх середнє арифметичне значення.

In [ ]:
a = np.random.randint(1, 101, size=(11, 11))
sum_a = np.sum(a)
print("Матриця")
print(a)
print("Сума елементів матриці:")
print(sum_a)

Матриця
[[-8.51412617  5.22913401  9.1287439   7.48096798  2.89036273  9.42816533
   5.83680661 -6.69299823  2.29384738]
 [ 1.35014087 -2.70016011  7.57682712 -7.45371169  3.01595318  1.35058132
  -1.75656385 -4.7072878  -6.17682992]
 [-9.00386969  4.60559837 -8.40051125 -3.75139917  3.04950779 -7.92490014
   1.33184123  9.97611121  0.09507715]
 [-0.44563102 -3.37750767  3.5507486  -2.972355   -0.36926936  5.00136287
   5.6236558   5.5239438   5.96793181]
 [ 2.68470048 -1.96077916 -3.83766788 -5.27921781 -8.16013208 -4.05269364
   1.08817977 -1.19300694  8.70068428]
 [-8.5073207   5.21951218 -1.462108    6.7975632  -2.97125694 -2.95052753
  -1.9605664  -6.48866082  7.83875838]
 [-0.5237632   2.85952136 -3.58032149  0.3088137  -9.45168093 -1.41200238
  -6.984141    7.96667333 -5.94573643]
 [ 5.0424401   7.3488649   7.01891748 -4.68647078  0.40636488 -5.62862695
  -7.4440826  -5.9946112  -0.3500465 ]
 [ 9.01651289 -9.47936858 -3.2501642   1.19936946  8.80786653 -3.73117426
  -0.11425738 

15. Створіть матрицю розміром 7x7, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить найменше ціле значення в кожному рядку матриці.

In [ ]:
a = np.random.rand(3, 3)
print("Матриця:")
print(a)

# Обчислення сум елементів кожного рядка матриці
row_sums = a.sum(axis=1)

# Перетворення одновимірного масиву на вектор-стовпчик
col_vec = row_sums.reshape((-1, 1))

print("Вектор-стовпчик з сумами елементів кожного рядка:")
print(col_vec)

Перша матриця:
[[ 0.48566029  0.09100415  0.08865893  0.08057764 -0.15705739 -0.0197939
   0.48293564  0.49924395  0.44617676]
 [ 0.36772801  0.03556754  0.2458348  -0.2318558   0.3904391  -0.39842551
   0.23431596 -0.32991497  0.47936254]
 [-0.08375673  0.46267879 -0.49574316  0.30002235 -0.11138158 -0.44570049
   0.05006199  0.03865413  0.03689482]
 [-0.47355087  0.12457577 -0.44618255  0.01888483  0.08413897  0.02284725
   0.38827181 -0.08856551  0.22484802]
 [-0.06740509 -0.48723634  0.03982014  0.09875491 -0.41178018  0.02601341
   0.08173397 -0.27022825 -0.03713124]
 [ 0.03250284 -0.14174031  0.24824842 -0.38197915  0.14307226 -0.41447699
  -0.24312139  0.15811149  0.29606618]
 [ 0.37511397  0.08682625 -0.15100257  0.21767017  0.44927242  0.406155
  -0.35534518  0.14409228 -0.24397774]
 [ 0.36997818  0.19857907 -0.00596784  0.45644629  0.04520184  0.05391566
  -0.15559649 -0.21658973 -0.13535904]
 [-0.4792882  -0.37627547 -0.3090308   0.44318948 -0.32290646  0.35508498
  -0.05782

В практичній роботі я використовував бібліотеку Numpy.Також я працював з функціями бібліотеки - Arange, Reshape, Random, Randint, Uniform.